import { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';

const initialBook = { titulo: '', sinopsis: '', url_portada: '', edad_objetivo: 0, autor_id: '', genero_id: '' };

const DashboardAdmin = () => {
  const navigate = useNavigate();
  const [usuario] = useState(() => { const guardado = localStorage.getItem('usuario_glancd'); return guardado ? JSON.parse(guardado) : null; });
  const [libros, setLibros] = useState([]); const [autores, setAutores] = useState([]); const [generos, setGeneros] = useState([]);
  const [cargando, setCargando] = useState(true); const [error, setError] = useState('');
  const [modal, setModal] = useState(null); const [bookId, setBookId] = useState(null); const [form, setForm] = useState(initialBook);
  const [autorForm, setAutorForm] = useState({ nombre_completo: '', biografia: '', url_foto: '' }); const [generoForm, setGeneroForm] = useState({ nombre: '', edad_minima: 0 });
  const urlBase = import.meta.env.VITE_API_LIBROS || 'http://localhost:8001';
  const config = () => ({ headers: { Authorization: `Bearer ${localStorage.getItem('token_glancd')}` } });

  const cargar = useCallback(async () => {
    try { setCargando(true); const [a, b, c] = await Promise.all([axios.get(`${urlBase}/api/libros/`, config()), axios.get(`${urlBase}/api/autores/`, config()), axios.get(`${urlBase}/api/generos/`, config())]); setLibros(a.data); setAutores(b.data); setGeneros(c.data); setError(''); }
    catch { setError('No se pudo cargar la información del catálogo.'); } finally { setCargando(false); }
  }, [urlBase]);
  useEffect(() => { const saved = localStorage.getItem('usuario_glancd'); if (!localStorage.getItem('token_glancd') || !saved) { navigate('/'); return; } const data = JSON.parse(saved); if (data.rol !== 'administrador') { navigate('/dashboard'); return; } const timer = window.setTimeout(cargar, 0); return () => window.clearTimeout(timer); }, [navigate, cargar]);
  const abrirLibro = (libro = null) => { setBookId(libro?.id || null); setForm(libro ? { titulo: libro.titulo || '', sinopsis: libro.sinopsis || '', url_portada: libro.url_portada || '', edad_objetivo: libro.edad_objetivo || 0, autor_id: libro.autor_id || '', genero_id: libro.genero_id || '' } : initialBook); setModal('libro'); };
  const guardarLibro = async (event) => { event.preventDefault(); const payload = { ...form, autor_id: form.autor_id || null, genero_id: form.genero_id ? Number(form.genero_id) : null }; try { await (bookId ? axios.put(`${urlBase}/api/libros/${bookId}`, payload, config()) : axios.post(`${urlBase}/api/libros/`, payload, config())); setModal(null); cargar(); } catch { setError('No se pudo guardar el libro. Revisa los datos e inténtalo de nuevo.'); } };
  const eliminar = async (id, titulo) => { if (!window.confirm(`¿Eliminar “${titulo}”?`)) return; try { await axios.delete(`${urlBase}/api/libros/${id}`, config()); cargar(); } catch { setError('No se pudo eliminar el libro.'); } };
  const guardarAutor = async (event) => { event.preventDefault(); try { const respuesta = await axios.post(`${urlBase}/api/autores/`, autorForm, config()); setAutores((actual) => [...actual, respuesta.data]); setForm((actual) => ({ ...actual, autor_id: respuesta.data.id })); setAutorForm({ nombre_completo: '', biografia: '', url_foto: '' }); setModal('libro'); } catch { setError('No se pudo crear el autor.'); } };
  const guardarGenero = async (event) => { event.preventDefault(); try { const respuesta = await axios.post(`${urlBase}/api/generos/`, { ...generoForm, edad_minima: Number(generoForm.edad_minima) || 0 }, config()); setGeneros((actual) => [...actual, respuesta.data]); setForm((actual) => ({ ...actual, genero_id: respuesta.data.id })); setGeneroForm({ nombre: '', edad_minima: 0 }); setModal('libro'); } catch { setError('No se pudo crear el género.'); } };
  if (!usuario) return <div className="page-loading">Verificando acceso…</div>;
  return <div className="admin-shell"><aside className="admin-sidebar"><a className="brand brand-light" href="/dashboard-admin">glancd<span>.</span></a><p className="admin-kicker">Administración</p><nav><a className="active" href="#catalogo">Catálogo</a><a href="#autores">Autores <span>{autores.length}</span></a><a href="#generos">Géneros <span>{generos.length}</span></a><a className="disabled" href="#usuarios">Usuarios <small>pronto</small></a></nav><div className="admin-profile"><span>{usuario.nombre?.[0] || 'A'}</span><div><strong>{usuario.nombre}</strong><small>Administrador</small></div></div><button className="sidebar-logout" onClick={() => { localStorage.clear(); navigate('/'); }}>Cerrar sesión</button></aside>
    <main className="admin-main"><header className="admin-header"><div><p className="eyebrow">Centro de control</p><h1>Buenos días, {usuario.nombre}.</h1><p>Cuida las historias que llegan a la comunidad.</p></div><button className="button button-primary" onClick={() => abrirLibro()}>+ Añadir libro</button></header>
      <section className="admin-stats"><div><span>Libros publicados</span><strong>{libros.length}</strong><small>en el catálogo</small></div><div><span>Autores</span><strong>{autores.length}</strong><small>registrados</small></div><div><span>Géneros</span><strong>{generos.length}</strong><small>para explorar</small></div></section>
      <section id="catalogo" className="management-card"><div className="management-head"><div><h2>Catálogo editorial</h2><p>Gestiona las lecturas visibles en Glancd.</p></div><span>{libros.length} registros</span></div>{error && <div className="notice notice-error">{error}</div>}{cargando ? <div className="empty-state">Cargando catálogo…</div> : <div className="admin-table"><div className="table-row table-label"><span>Libro</span><span>Autor</span><span>Género</span><span>Edad</span><span>Acciones</span></div>{libros.map((libro) => <div className="table-row" key={libro.id}><div className="admin-book"><div>{libro.url_portada ? <img src={libro.url_portada} alt="" /> : libro.titulo?.[0]}</div><strong>{libro.titulo}</strong></div><span>{libro.autor ? `${libro.autor.nombre_completo}` : 'Sin autor'}</span><span>{libro.genero?.nombre || 'Sin género'}</span><span>+{libro.edad_objetivo || 0}</span><div className="row-actions"><button onClick={() => abrirLibro(libro)}>Editar</button><button className="danger" onClick={() => eliminar(libro.id, libro.titulo)}>Eliminar</button></div></div>)}</div>}</section></main>
    {modal === 'libro' && <div className="modal-backdrop"><section className="modal-card"><button className="modal-close" onClick={() => setModal(null)}>×</button><p className="eyebrow">{bookId ? 'Editar registro' : 'Nueva lectura'}</p><h2>{bookId ? 'Ajusta los detalles.' : 'Añade una historia.'}</h2><form className="admin-form" onSubmit={guardarLibro}><label>Título<input required value={form.titulo} onChange={(e) => setForm({ ...form, titulo: e.target.value })} /></label><div className="form-pair"><label>Autor<div className="select-add"><select value={form.autor_id} onChange={(e) => setForm({ ...form, autor_id: e.target.value })}><option value="">Selecciona un autor</option>{autores.map((a) => <option key={a.id} value={a.id}>{a.nombre_completo}</option>)}</select><button type="button" onClick={() => setModal('autor')}>+</button></div></label><label>Género<div className="select-add"><select value={form.genero_id} onChange={(e) => setForm({ ...form, genero_id: e.target.value })}><option value="">Selecciona un género</option>{generos.map((g) => <option key={g.id} value={g.id}>{g.nombre}</option>)}</select><button type="button" onClick={() => setModal('genero')}>+</button></div></label></div><label>Sinopsis<textarea rows="4" value={form.sinopsis} onChange={(e) => setForm({ ...form, sinopsis: e.target.value })} /></label><div className="form-pair"><label>URL de portada<input type="url" value={form.url_portada} onChange={(e) => setForm({ ...form, url_portada: e.target.value })} /></label><label>Edad sugerida<input min="0" type="number" value={form.edad_objetivo} onChange={(e) => setForm({ ...form, edad_objetivo: Number(e.target.value) || 0 })} /></label></div><div className="modal-actions"><button className="button button-ghost" type="button" onClick={() => setModal(null)}>Cancelar</button><button className="button button-primary" type="submit">Guardar libro</button></div></form></section></div>}
    {modal === 'autor' && <div className="modal-backdrop"><section className="modal-card modal-small"><button className="modal-close" onClick={() => setModal('libro')}>×</button><p className="eyebrow">Autor nuevo</p><h2>Una nueva voz.</h2><form className="admin-form" onSubmit={guardarAutor}><label>Nombre completo<input required value={autorForm.nombre_completo} onChange={(e) => setAutorForm({ ...autorForm, nombre_completo: e.target.value })} /></label><label>Biografía<textarea rows="3" value={autorForm.biografia} onChange={(e) => setAutorForm({ ...autorForm, biografia: e.target.value })} /></label><div className="modal-actions"><button className="button button-ghost" type="button" onClick={() => setModal('libro')}>Volver</button><button className="button button-primary">Guardar autor</button></div></form></section></div>}
    {modal === 'genero' && <div className="modal-backdrop"><section className="modal-card modal-small"><button className="modal-close" onClick={() => setModal('libro')}>×</button><p className="eyebrow">Género nuevo</p><h2>Abre una categoría.</h2><form className="admin-form" onSubmit={guardarGenero}><label>Nombre<input required value={generoForm.nombre} onChange={(e) => setGeneroForm({ ...generoForm, nombre: e.target.value })} /></label><label>Edad mínima<input min="0" type="number" value={generoForm.edad_minima} onChange={(e) => setGeneroForm({ ...generoForm, edad_minima: e.target.value })} /></label><div className="modal-actions"><button className="button button-ghost" type="button" onClick={() => setModal('libro')}>Volver</button><button className="button button-primary">Guardar género</button></div></form></section></div>}</div>;
};
export default DashboardAdmin;
